/// Flutter icons MyIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcon
///      fonts:
///       - asset: fonts/MyIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyIcon {
  MyIcon._();

  static const String _kFontFam = 'MyIcon';
  static const String? _kFontPkg = null;

  static const IconData resetPath = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resetWall = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData maze = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
